### ISSUE TITLE
Proj.direc_out is unused

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#103]
Currently there is no way for the user to specify an output directory for aospy data.  Instead we default to the GFDL scratch or archive locations.  How should we approach this?

The fastest fix is to just override the scratch directory if the user specifies a `direc_out` in a `Proj` constructor (see the [direc-out branch on my fork](https://github.com/spencerkclark/aospy/blob/direc-out/aospy/calc.py#L180-L188)), but on thinking about it more I'm not sure if that's a safe solution.  If someone is using aospy on a machine where they have root privileges (e.g. a personal laptop), and they neglect to specify a `direc_out` for their project, would things still run, and a `/work/$USER/` directory be created at the root level?  I don't think this is our intended behavior.  Perhaps a sensible default would be the current working directory?

**Comment by spencerahill** [comment]
Good catch.

The "scratch" v. "archive" nomenclature also isn't really universal: for a personal computer, there's only one filesystem, and neither of these titles is a good fit.

So, this would be expanding the modification appreciably, but what if we switch to "primary" and "secondary" as the labels?  The `direc_out` attribute is then mandatory and specifies the root of the primary output directory.  Maybe it can also accept a two-sequence of strings; if the latter, the first is considered the primary and the second the secondary?  It's not quite this simple though, since the logic is different in the scratch and archive cases...

Thoughts?

**Comment by spencerkclark** [comment]
What if we split things into two keyword arguments in the Proj constructor?  Maybe we could use `direc_out` for the directory of the untarred data, and `tar_direc_out` for the directory containing the tar files?

**Comment by spencerahill** [comment]
Is there a way to keep it more general?  Maybe down the line we want to support other write functionality.  I.e. we would have `output_direc` and `output_strategy` (names open to change).  `output_strategy` would specify which output method to use; the default would be what is now "scratch" (not sure what the best name would be...just "standard"?), and for now the only other option would be what is now "archive" (I like "tar" there).

(Also possible I'm getting carried away, given the time crunch of fixing this.  Totally fine with a quick fix and then re-visiting this after the workshop)

**Comment by spencerkclark** [comment]
Yeah I think I'll go with a quick fix for now, if that's OK.  I think generalizing this might fall under the umbrella of the broader refactor of Calc.  

Splitting into two kwargs actually would be pretty painless (and not too breaking a change for both of us, since this gets defined at the Proj level).  I'll put together a quick PR.

**Comment by spencerahill** [comment]
Sounds good.  I'll make an issue to track the longer-term solution.

**Comment by spencerahill** [comment]
Closed by #105
