### ISSUE TITLE
Remove legacy code in calc meant to enable calculations involving multiple runs and models

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#117]
As part of #90 I will be making a first step towards a refactor of calc.py.  Before doing that, however, I think it might be a good idea to clean up some of the code that was at one point meant as a crude way to enable calculations involving multiple runs and models.  To my knowledge this functionality has been broken for some time, is not tested or documented, and what's left of the logic seems to muddy things a fair amount in calc.py.

@spencerahill what are your thoughts on this?  I know eventually we'll probably want to revisit this type of functionality, but for now do you think we should try for a start fresh?

**Comment by spencerahill** [comment]
I'm mostly in favor of dropping this code, but it might be quite difficult, or at least quite time consuming.  That logic is hard-baked all over `Calc` (and maybe elsewhere), mostly in the form of strange nested lists, etc.

Is it causing problems for you on #90?  If yes, then I'd say let's go for it now.  Otherwise, it might be more prudent to finish #90 first and then tackle this.
