### ISSUE TITLE
BUG: Workaround for datetimes with years less than 1678 not valid for reference date not set to 0001-01-01

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#188]
This came up in helping set up aospy for someone looking at an AM2 run which was run for years 781 to 800.  The reference date in the units attribute of the time variable in the output files was:
```
double time(time) ;
		time:long_name = "time" ;
		time:units = "days since 0761-01-01 00:00:00" ;
		time:cartesian_axis = "T" ;
		time:calendar_type = "NOLEAP" ;
		time:calendar = "NOLEAP" ;
		time:bounds = "time_bounds" ;
```
January 1st, 0761.  

The current logic in `utils.times.numpy_datetime_workaround_encode_cf` looks like:

```python
def numpy_datetime_workaround_encode_cf(ds):
    time = ds[internal_names.TIME_STR]
    units = time.attrs['units']
    units_yr = units.split(' since ')[1].split('-')[0]
    min_yr_decoded = xr.decode_cf(time.to_dataset(name='dummy'))
    min_date = min_yr_decoded[internal_names.TIME_STR].values[0]
    if isinstance(min_date, np.datetime64):
        return ds, pd.Timestamp(min_date).year
    else:
        min_yr = min_date.year
        new_units_yr = pd.Timestamp.min.year + 2 - min_yr
        new_units = units.replace(units_yr, str(new_units_yr))

        for VAR_STR in internal_names.TIME_VAR_STRS:
            if VAR_STR in ds:
                var = ds[VAR_STR]
                var.attrs['units'] = new_units
        return ds, min_yr
```

In the case of these files, `min_yr` was 781; therefore `new_units_yr` was set to 1679 - 781 = 898.  This made the new reference date in the files `0898-01-01 00:00:00`.  But, since the raw time values (originally encoded as `"days since 0761-01-01 00:00:00"`) had values
```
time = 7315.5, 7345, 7374.5, 7405, 7435.5, 7466, 7496.5, 7527.5, 7558,
    7588.5, 7619, 7649.5, 7680.5 ...
}
```
the newly decoded times (using the new reference date), still were not in the Timestamp-valid range.  E.g. 7315.5 is only roughly 20 years, so the first value would be decoded as in year 918 rather than in 1678.

I *think* a solution to this would be to change the line `new_units_yr = pd.Timestamp.min.year + 2 - min_yr` to `new_units_yr = pd.Timestamp.min.year + 1 - min_yr + int(units_yr)` in the above method, but I haven't thought through it carefully yet.

**Comment by spencerahill** [comment]
Thanks for the report.

>I think a solution to this would be to change the line new_units_yr = pd.Timestamp.min.year + 2 - min_yr to new_units_yr = pd.Timestamp.min.year + 1 - min_yr + int(units_yr) in the above method, but I haven't thought through it carefully yet.

Yes, I think that's correct.

My thought process: Ultimately the point of this endeavor is to apply an offset to the given date range such that the first timestep of the input data is at the (nearly) earliest time within the valid numpy date-range, while still retaining enough information to then eventually switch back to the actual dates.  So, in this particular case, we'd want the units to roughly be days since `pd.Timestamp.min.year + 1 - 20 years`.  Taking the difference between the units year and the earliest year does give us that 20 years.

So all that is to say I think your new logic would be correct.  I'd recommend first writing a test that fails for this case or one similar, then implement the new logic such that it passes.
