### ISSUE TITLE
confusing attrs on the sample data

### ISSUE THREAD

**Issue by micahkim23** [spencerahill/aospy#214]
```python
>>> xr.open_mfdataset(os.path.join(rootdir, '00050101.precip_monthly.nc'), decode_times=False)
<xarray.Dataset>
Dimensions:            (lat: 64, latb: 65, lon: 128, lonb: 129, nv: 2, time: 12)
Coordinates:
  * lonb               (lonb) float64 -1.406 1.406 4.219 7.031 9.844 12.66 ...
  * lon                (lon) float64 0.0 2.812 5.625 8.438 11.25 14.06 16.88 ...
  * latb               (latb) float64 -90.0 -86.58 -83.76 -80.96 -78.16 ...
  * lat                (lat) float64 -87.86 -85.1 -82.31 -79.53 -76.74 ...
  * time               (time) float64 1.476e+03 1.504e+03 1.535e+03 ...
  * nv                 (nv) float64 1.0 2.0
Data variables:
    condensation_rain  (time, lat, lon) float64 5.905e-06 5.728e-06 ...
    convection_rain    (time, lat, lon) float64 0.0 0.0 0.0 0.0 0.0 ...
    time_bounds        (time, nv) float64 1.46e+03 1.491e+03 1.491e+03 ...
    average_DT         (time) float64 31.0 28.0 31.0 30.0 31.0 30.0 31.0 ...
    zsurf              (lat, lon) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
Attributes:
    grid_tile:  N/A
    title:      FMS Model results
    grid_type:  regular
    filename:   00050101.atmos_month.nc
```
The filename attribute confused me because I wasn't sure whether or not `00050101.atmos_month.nc` was created somewhere on my machine.

**Comment by spencerahill** [comment]
Thanks for the report.  I agree that this is confusing.  In fact, all of the file-level attributes -- `grid_tile`, `title`, `grid_type`, and `filename` -- are likely to be confusing to new users (They were presumably auto-generated by the numerical model but are unhelpful for our purposes).  So I'm inclined to remove them entirely.

This could actually be a good one for you to tackle, @micahkim23: just load all the sample data files using `xarray`, then delete the Dataset-level attributes...I think you can use `del` on each one.  Or since we're removing them all, I think you can just do `ds.attrs = {}`.  See http://xarray.pydata.org/en/stable/data-structures.html for more.  Then save the resulting dataset to disk via `to_netcdf`, overwriting the existing one.

**Comment by spencerahill** [comment]
Let me also use this to introduce @micahkim23 to @spencerkclark and everyone else following along.  Micah is a UCLA junior undergrad who will be working with me on aospy over the remainder of the fall quarter, and potentially beyond.  We're planning on tackling some of the "low-hanging fruit" Issues as a way of bringing Micah up to speed to start.  Welcome aboard!

**Comment by spencerkclark** [comment]
@micahkim23 great to have you on board!  I agree this is a good first issue.  Don't hesitate to ask questions wherever things are confusing; I'm happy to help out where I can.

**Comment by micahkim23** [comment]
@spencerkclark nice to meet you. I'm excited to be working on the project.
