### ISSUE TITLE
AM3 lon_bounds, lat_bounds not being read from grid files

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#38]
(Most recent commit is  cda8fe7, although this bug no doubt stems from changes in a prior commit)

One of the grid files is: `/archive/Spencer.Hill/am3/am3clim_hurrell/gfdl.ncrc2-intel-prod-openmp/pp/atmos/atmos.static.nc`.  This netCDF file has `lat_bnds` and `lon_bnds` variables, and those strings are in the list of strings to check for, but for some reason they aren't being found by `Model._get_grid_attr`.

**Comment by spencerkclark** [comment]
I think this is my fault -- I think the issue is here in [`Model._set_mult_grid_attr`](https://github.com/spencerahill/aospy/blob/develop/aospy/model.py#L149-L159).  With the `break` keyword it looks like the loop will stop regardless after it tries the first external name.  In addition, the way the body of the loop is currently written it looks like it will overwrite the attribute if the loop were allowed to run more than once (so you might end up with `None` attributes if you got rid of the `break` keyword).  

Would something like this solve those two problems?  Do we need to make sure that an attribute is set to `None` if it isn't found?

``` python
try:
    for name_int, names_ext in grid_attrs.items():
        for name in names_ext:
        # Rename all coordinates such that they match specified internal names.
        grid_attr = self._get_grid_attr(grid_objs, name)
        if grid_attr:
            renamed_attrs = self._rename_coords(grid_attr)
            setattr(self, name_int, renamed_attrs)
            break
        setattr(self, name_int, renamed_attrs)
except:
    raise
```

**Comment by spencerahill** [comment]
Yes this block is definitely the source of the problem.  I actually coded up a fix along with some other fixes to Model that I'll push soon.  Thanks!
